spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 994127
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      query-timeout: 30

server:
  port: 8080